package ins.accfee.report.schema.model;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * POJO Class 预提费用余额
 * Tue Apr 26 17:13:18 CST 2016 
 * org.a
 */
@Entity
@Table(name = "EAccountFeeLast")
public class EAccountFeeLastView implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private Long  reportdataId ;
	private Long  dataId       ;
	private String  str1         ;
	private String  str2         ;
	private String  str3         ;
	private String  str4         ;
	private String  str5         ;
	private String  str6         ;
	private String  str7         ;
	private String  str8         ;
	private String  str9         ;
	private String  hahawolegchacha;
	private String userByWaterId;
	
	public void setUserByWaterId(String userByWaterId){
		this.userByWaterId = userByWaterId;
	}
	
	public String getUserByWaterId(){
		return this.userByWaterId;
	}
	